apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testgo0127a-gitops
  description: This is GitOps manifest for testgo0127a   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testgo0127a
    backstage.io/kubernetes-id: testgo0127a 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: testgo0127a   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testgo0127a
